import { center, teachers, subjects, schedules, resources, gallery, testimonials, announcement } from './data.js';

const escape = value => String(value ?? '').replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
const paths = {
  arrow: '<path d="M7 17 17 7M7 7h10v10"/>', right: '<path d="M5 12h14m-6-6 6 6-6 6"/>',
  book: '<path d="M12 7v14m0-14C9 4 4 4 2 5v14c3-1 7-1 10 2 3-3 7-3 10-2V5c-2-1-7-1-10 2Z"/>',
  cap: '<path d="m2 9 10-5 10 5-10 5L2 9Zm4 2v6c4 3 8 3 12 0v-6m4-2v7"/>',
  pin: '<path d="M20 10c0 6-8 12-8 12S4 16 4 10a8 8 0 1 1 16 0Z"/><circle cx="12" cy="10" r="2.5"/>',
  check: '<path d="m5 12 4 4L19 6"/>', menu: '<path d="M4 6h16M4 12h16M4 18h16"/>', close: '<path d="m6 6 12 12M6 18 18 6"/>',
  users: '<path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2m20 0v-2a4 4 0 0 0-3-3.87M16 3.13a4 4 0 0 1 0 7.75"/><circle cx="9" cy="7" r="4"/>',
  target: '<circle cx="12" cy="12" r="9"/><circle cx="12" cy="12" r="5"/><circle cx="12" cy="12" r="1"/>',
  calendar: '<rect x="3" y="5" width="18" height="16" rx="2"/><path d="M16 3v4M8 3v4M3 11h18m-13 5h2m4 0h2"/>',
  sigma: '<path d="M18 4H6l7 8-7 8h12"/>', atom: '<ellipse cx="12" cy="12" rx="10" ry="4.5"/><ellipse cx="12" cy="12" rx="10" ry="4.5" transform="rotate(60 12 12)"/><ellipse cx="12" cy="12" rx="10" ry="4.5" transform="rotate(120 12 12)"/>',
  leaf: '<path d="M20 3c-1 5 2 11-4 15a7 7 0 0 1-10-10c4-4 9-2 14-5ZM3 21 15 9"/>',
  languages: '<path d="M3 5h12M9 3v2M5 5c1 6 4 9 8 11M13 5c-1 6-5 10-10 12m11 4 4-10 4 10m-6-4h4"/>',
  thought: '<path d="M9 18h6m-5 3h4m-6-7a6 6 0 1 1 8 0c-1 1-1 2-1 4H9c0-2 0-3-1-4Z"/>',
  pen: '<path d="m15 5 4 4M4 20l4-1L21 6a2.8 2.8 0 0 0-4-4L4 15l-1 6Z"/>',
  chart: '<path d="M3 3v18h18M7 15l4-4 4 2 6-8"/>',
  file: '<path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8l-6-6Zm0 0v6h6M8 13h8m-8 4h5"/>',
  clock: '<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>',
  phone: '<path d="M22 16.9v3a2 2 0 0 1-2.2 2 19.8 19.8 0 0 1-8.6-3.1 19.5 19.5 0 0 1-6-6 19.8 19.8 0 0 1-3.1-8.7A2 2 0 0 1 4.1 2h3a2 2 0 0 1 2 1.7c.1 1 .4 2 .7 2.9a2 2 0 0 1-.5 2.1L8 10a16 16 0 0 0 6 6l1.3-1.3a2 2 0 0 1 2.1-.5c.9.3 1.9.6 2.9.7a2 2 0 0 1 1.7 2Z"/>',
  instagram: '<rect x="3" y="3" width="18" height="18" rx="5"/><circle cx="12" cy="12" r="4"/><path d="M17.5 6.5h.01"/>',
  image: '<rect x="3" y="3" width="18" height="18" rx="2"/><circle cx="8.5" cy="8.5" r="1.5"/><path d="m21 15-5-5L5 21"/>',
  whatsapp: '<path d="M20.5 3.5a11 11 0 0 0-17.3 13L2 22l5.7-1.5A11 11 0 0 0 20.5 3.5Z"/><path d="M8.2 6.8c-.4 0-1.3.6-1.3 1.8 0 2.4 3.7 6.9 7 7.7 1.5.4 2.9-.7 2.9-1.7l-2.7-1.3-.9 1c-1.7-.7-3-2-3.8-3.5l.9-1-1.1-2.8Z"/>'
};
function icon(name, cls = '') { return `<svg class="icon ${cls}" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.65" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${paths[name] || paths.book}</svg>`; }
function wa(message = center.registrationMessage) { return `https://wa.me/${center.whatsapp}?text=${encodeURIComponent(message)}`; }
function whatsappButton(label, cls = 'btn-primary') { return `<a class="btn ${cls}" href="${wa()}" target="_blank" rel="noopener noreferrer">${escape(label)}${icon('arrow')}</a>`; }
function brand() { return `<a class="brand" href="#accueil" aria-label="Centre Joundi, accueil">${center.logo ? `<img src="${escape(center.logo)}" alt="Centre Joundi" width="43" height="43" />` : `<span class="brand-mark" aria-hidden="true">${icon('book')}<i></i></span>`}<span>CENTRE JOUNDI<small>DE SOUTIEN</small></span></a>`; }
const links = [['accueil', 'Accueil'], ['centre', 'Le Centre'], ['professeurs', 'Nos Professeurs'], ['matieres', 'Matières'], ['planning', 'Planning'], ['ressources', 'Ressources'], ['contact', 'Contact']];
function navLinks() { return links.map(([id, label]) => `<a href="#${id}">${label}</a>`).join(''); }
function photo(src, alt, className = '', eager = false, options = {}) { return `<img class="${className}" src="${escape(src)}" alt="${escape(alt)}" loading="${eager ? 'eager' : 'lazy'}" ${eager ? 'fetchpriority="high"' : ''} decoding="async" width="${options.width || 400}" height="${options.height || 600}" style="object-position:${escape(options.position || '50% 0%')}" />`; }
function teacherCard(t) { return `<article class="teacher-card"><div class="teacher-portrait">${photo(t.photo, `${t.name} - ${t.subject} - Centre Joundi`, '', false, t)}<div class="portrait-levels">${t.levels.map(l => `<span>${l}</span>`).join('')}</div></div><div class="teacher-info"><p class="teacher-subject">${escape(t.subject)}</p><h3>${escape(t.name)}</h3><p>${escape(t.detail)}</p><a href="${wa(`Bonjour Centre Joundi, je souhaite des informations sur les cours de ${t.subject} avec ${t.name}.`)}" target="_blank" rel="noopener noreferrer" aria-label="Se renseigner sur les cours de ${escape(t.name)}">Se renseigner ${icon('arrow')}</a></div></article>`; }

document.querySelector('#app').innerHTML = `
  <div class="topbar"><div class="container"><span>${icon('pin')} Hay El Salam, Safi</span><span>Un objectif commun. <b>Votre réussite.</b></span><a href="tel:+${center.whatsapp}">${icon('phone')}${escape(center.phone)}</a></div></div>
  <header class="header"><div class="container nav-wrap">${brand()}<nav class="desktop-nav" aria-label="Navigation principale">${navLinks()}</nav><div class="nav-actions">${whatsappButton('Inscription', 'btn-small')}<button class="menu-toggle" aria-label="Ouvrir le menu" aria-expanded="false" aria-controls="mobile-nav">${icon('menu')}</button></div></div><nav id="mobile-nav" class="mobile-nav" aria-label="Navigation mobile" hidden>${navLinks()}${whatsappButton('S’inscrire via WhatsApp')}</nav></header>
  <main id="main">
    ${announcement ? `<aside class="announcement container">${escape(announcement.text)} <a href="${escape(announcement.link)}">${escape(announcement.label)}</a></aside>` : ''}
    <section id="accueil" class="hero"><div class="container hero-grid"><div class="hero-content"><p class="eyebrow"><span></span> VOTRE CAP VERS LE BAC</p><h1>Votre réussite<br>commence <em>ici.</em></h1><p class="hero-description">Un accompagnement de qualité pour préparer votre BAC avec méthode, confiance et excellence.</p><div class="hero-actions">${whatsappButton('S’inscrire maintenant')}<a class="text-link" href="#professeurs">Découvrir nos professeurs ${icon('right')}</a></div><div class="hero-note"><span class="note-icon">${icon('cap')}</span><p>À chaque étape, à vos côtés.<small>Soutien scolaire à Safi · 1BAC & 2BAC</small></p></div></div><div class="hero-visual">${center.heroImage ? photo(center.heroImage, center.heroImageAlt, 'hero-photo', true) : `<div class="academic-art" role="img" aria-label="Illustration typographique : objectif BAC, méthode, confiance et réussite"><div class="art-top"><span>CENTRE JOUNDI</span><span>SAFI, MAROC</span></div><div class="art-orbits"></div><div class="art-word"><small>ENSEMBLE, VISONS</small><strong>le BAC<span>.</span></strong></div><div class="art-steps"><span>01 <b>Comprendre</b></span><span>02 <b>Pratiquer</b></span><span>03 <b>Progresser</b></span></div><div class="art-bottom">LE SAVOIR OUVRE DES PERSPECTIVES ${icon('arrow')}</div></div>`}<div class="hero-level-card"><span>${icon('book')}</span><div><strong>1BAC <i>&</i> 2BAC</strong><small>Une préparation, un avenir.</small></div></div><div class="hero-caption"><span class="line"></span> L’ambition se construit, ensemble.</div></div></div></section>
    <div class="trust-strip"><div class="container trust-grid">${[['cap', '1BAC & 2BAC', 'Un parcours adapté'], ['users', 'Professeurs spécialisés', 'Une équipe engagée'], ['file', 'Préparation aux examens', 'Du cours à la pratique'], ['target', 'Suivi pédagogique', 'Progresser avec méthode']].map(([i, t, s]) => `<div>${icon(i)}<p><strong>${t}</strong><span>${s}</span></p></div>`).join('')}</div></div>
    <section id="centre" class="section"><div class="container about-grid"><div class="about-visual">${photo(center.aboutImage, center.aboutImageAlt, '', false, { width: 195, height: 228, position: '50% 35%' })}<div class="about-tag"><span>Notre conviction</span><strong>Le bon accompagnement<br>fait la différence.</strong></div></div><div class="about-content"><p class="eyebrow">LE CENTRE JOUNDI</p><h2>Un accompagnement<br>pensé pour votre <em>réussite.</em></h2><p>Chaque élève a son ambition. Notre rôle : lui donner les repères, la méthode et la confiance pour avancer.</p><p>À Hay El Salam, Safi, Centre Joundi accompagne les élèves du cycle qualifiant avec des professeurs spécialisés, des cours structurés et une préparation progressive aux examens.</p><ul class="check-list"><li>${icon('check')} Des explications claires pour maîtriser l’essentiel</li><li>${icon('check')} Des exercices pour transformer les acquis en réflexes</li><li>${icon('check')} Un accompagnement adapté à votre niveau</li></ul><a class="text-link" href="#contact">Faisons connaissance ${icon('right')}</a></div></div></section>
    <section id="professeurs" class="section teachers-section"><div class="container"><div class="section-heading"><div><p class="eyebrow">LES VISAGES DE VOTRE RÉUSSITE</p><h2>Une équipe engagée<br>à vos côtés.</h2></div><p>Des professeurs spécialisés dans leur matière.<br>Une même envie : vous aider à progresser.</p></div><div class="filter-row" role="group" aria-label="Filtrer les professeurs par niveau"><button class="filter active" data-teacher-filter="all" aria-pressed="true">Tous les professeurs</button><button class="filter" data-teacher-filter="1BAC" aria-pressed="false">1BAC</button><button class="filter" data-teacher-filter="2BAC" aria-pressed="false">2BAC</button><span class="filter-note">L’expertise au service de votre parcours</span></div><div class="teacher-grid" id="teacher-grid">${teachers.map(teacherCard).join('')}</div><p id="teacher-status" class="sr-only" aria-live="polite"></p></div></section>
    <section id="matieres" class="section"><div class="container"><div class="section-heading"><div><p class="eyebrow">DES BASES SOLIDES, DANS CHAQUE DISCIPLINE</p><h2>Nos matières<span class="orange">.</span></h2></div><p>Sciences, langues et économie.<br>Trouvez le soutien qui vous correspond.</p></div><div class="subject-grid">${subjects.map(s => `<a class="subject-card" href="${wa(`Bonjour Centre Joundi, je souhaite connaître les cours de ${s.name} disponibles pour mon niveau et ma filière.`)}" target="_blank" rel="noopener noreferrer"><span class="subject-icon">${icon(s.icon)}</span><h3>${s.name}</h3><p>${s.levels.join(' · ')}</p>${icon('arrow', 'subject-arrow')}</a>`).join('')}</div><p class="section-footnote">Disponibilité des cours à confirmer avec le centre selon votre niveau et votre filière.</p></div></section>
    <section class="preparation-section"><div class="container preparation-grid"><div><p class="eyebrow light">LA MÉTHODE CENTRE JOUNDI</p><h2>Préparez votre BAC<br>avec <em>confiance.</em></h2><p>Avancer pas à pas, consolider les acquis, puis s’entraîner dans les conditions de l’examen. Une préparation qui donne du sens à chaque effort.</p><div class="approach-grid">${['Cours structurés', 'Exercices ciblés', 'Préparation aux contrôles', 'Examens régionaux', 'Examens nationaux', 'Révisions intensives'].map(t => `<span>${icon('check')}${t}</span>`).join('')}</div>${whatsappButton('Rejoindre Centre Joundi', 'btn-orange')}</div><div class="preparation-visual">${center.preparationImage ? photo(center.preparationImage, center.preparationImageAlt) : `<div class="method-card"><span class="method-label">VOTRE PARCOURS</span><div><b>01</b><p>Comprendre<small>Poser les bonnes bases.</small></p>${icon('book')}</div><div><b>02</b><p>S’entraîner<small>Faire de la méthode un réflexe.</small></p>${icon('pen')}</div><div><b>03</b><p>Prendre confiance<small>Aborder les examens sereinement.</small></p>${icon('target')}</div><span class="method-footer">Un cours après l’autre. Un pas vers votre avenir.</span></div>`}</div></div></section>
    <section id="planning" class="section"><div class="container"><div class="section-heading"><div><p class="eyebrow">ORGANISER SA RÉUSSITE</p><h2>Planning des cours<span class="orange">.</span></h2></div><a class="text-link" href="${wa('Bonjour Centre Joundi, pouvez-vous m’envoyer le planning des cours pour mon niveau ?')}" target="_blank" rel="noopener noreferrer">Recevoir le planning ${icon('arrow')}</a></div><div class="planning-toolbar"><div class="level-switch" role="group" aria-label="Niveau du planning"><button class="active" data-level="1BAC" aria-pressed="true">1BAC</button><button data-level="2BAC" aria-pressed="false">2BAC</button></div><label class="select-label">Matière <select id="schedule-subject"><option value="all">Toutes les matières</option>${subjects.map(s => `<option>${s.name}</option>`).join('')}</select></label><span class="schedule-key"><i></i> Horaires à confirmer</span></div><div id="schedule-grid" class="schedule-grid"></div><div id="schedule-notice" class="schedule-notice" aria-live="polite"></div></div></section>
    <section id="ressources" class="section resources-section"><div class="container"><div class="section-heading"><div><p class="eyebrow">APPRENDRE AU-DELÀ DU COURS</p><h2>Ressources pédagogiques<span class="orange">.</span></h2></div><p>Cours, exercices, examens et corrections.<br>Un espace pour poursuivre vos révisions.</p></div><div class="resource-grid">${resources.map((r, i) => `<article class="resource-card"><div class="resource-top">${icon(r.icon)}<span>DOCUMENTS PDF</span></div><h3>${r.subject}</h3><p>Cours & fiches d’exercices</p><div class="resource-bottom"><span>${r.documents.length ? `${r.documents.length} document${r.documents.length > 1 ? 's' : ''}` : 'Bientôt disponibles'}</span><button class="resource-button" data-resource="${i}" aria-label="${r.documents.length ? 'Voir les documents' : 'Consulter la disponibilité'} : ${r.subject}">${icon('arrow')}</button></div></article>`).join('')}</div><p class="section-footnote">Les documents seront ajoutés progressivement. En attendant, contactez votre professeur.</p></div></section>
    <section id="galerie" class="section"><div class="container"><div class="section-heading"><div><p class="eyebrow">APPRENDRE, PARTAGER, AVANCER</p><h2>La vie au Centre Joundi<span class="orange">.</span></h2></div><a class="text-link" href="https://www.instagram.com/${center.instagram}/" target="_blank" rel="noopener noreferrer">Suivez-nous sur Instagram ${icon('arrow')}</a></div><div class="gallery-grid">${gallery.map((g, i) => `<button class="gallery-item" data-gallery="${i}" aria-label="Agrandir : ${escape(g.alt)}">${photo(g.src, g.alt, '', false, g)}<span>${escape(g.caption)}${icon('arrow')}</span></button>`).join('')}</div></div></section>
    ${testimonials.length ? `<section class="section testimonials-section"><div class="container"><p class="eyebrow">LEURS PARCOURS, LEURS MOTS</p><h2>Ils partagent leur expérience.</h2><div class="testimonial-grid">${testimonials.map(t => `<figure><blockquote>« ${escape(t.quote)} »</blockquote><figcaption><strong>${escape(t.name)}</strong><span>${escape(t.detail)}</span></figcaption></figure>`).join('')}</div></div></section>` : ''}
    <section class="registration-section"><div class="container registration-inner"><div><p class="eyebrow">LE PROCHAIN PAS VOUS APPARTIENT</p><h2>Prêt à commencer<br>votre préparation ?</h2><p>Contactez Centre Joundi et trouvez<br>l’accompagnement adapté à votre niveau.</p></div><div class="registration-actions">${whatsappButton('S’inscrire via WhatsApp')}<a href="#contact" class="text-link">Nous contacter ${icon('right')}</a><span>Échangeons sur votre parcours.</span></div></div></section>
    <section id="contact" class="section"><div class="container contact-grid"><div><p class="eyebrow">PARLONS DE VOTRE AVENIR</p><h2>À votre écoute<span class="orange">.</span></h2><p class="contact-intro">Une question sur les cours ou l’inscription ?<br>Notre équipe vous accompagne.</p><div class="contact-details"><div>${icon('pin')}<p><strong>Venez nous rencontrer</strong>${escape(center.address)}, ${escape(center.city)}</p></div><a href="tel:+${center.whatsapp}">${icon('phone')}<p><strong>Appelez-nous</strong>${escape(center.phone)}</p></a><a href="https://www.instagram.com/${center.instagram}/" target="_blank" rel="noopener noreferrer">${icon('instagram')}<p><strong>Suivez notre actualité</strong>@${center.instagram}</p>${icon('arrow')}</a></div>${center.mapsEmbedUrl ? `<iframe class="map-frame" title="Localisation du Centre Joundi" src="${escape(center.mapsEmbedUrl)}" loading="lazy" referrerpolicy="no-referrer-when-downgrade" allowfullscreen></iframe>` : `<div class="map-placeholder">${icon('pin')}<div><strong>Hay El Salam, Safi</strong><span>Emplacement précis à ajouter</span></div><a href="${wa('Bonjour Centre Joundi, pouvez-vous m’envoyer votre localisation exacte à Safi ?')}" target="_blank" rel="noopener noreferrer" aria-label="Demander la localisation exacte">${icon('arrow')}</a></div>`}</div><form id="contact-form" class="contact-form"><h3>Faisons le premier pas.</h3><p>Votre message sera préparé dans WhatsApp.</p><div class="form-row"><label>Nom complet <span>*</span><input name="name" autocomplete="name" placeholder="Votre nom" required maxlength="100" /></label><label>Téléphone <span>*</span><input type="tel" name="phone" autocomplete="tel" placeholder="06 XX XX XX XX" required pattern="[+0-9 ]{8,25}" maxlength="25" title="Saisissez un numéro de téléphone valide (8 à 25 caractères)." /></label></div><div class="form-row"><label>Niveau <span>*</span><select name="level" required><option value="">Sélectionner</option><option>1BAC</option><option>2BAC</option></select></label><label>Matière <span>*</span><select name="subject" required><option value="">Sélectionner</option>${subjects.map(s => `<option>${s.name}</option>`).join('')}<option>Plusieurs matières</option></select></label></div><label>Votre message<textarea name="message" rows="4" maxlength="2000" placeholder="Parlez-nous de vos besoins…"></textarea></label><button type="submit" class="btn btn-primary">Envoyer via WhatsApp ${icon('arrow')}</button><p class="form-privacy">Vous pourrez relire et envoyer votre message dans WhatsApp. Aucune donnée du formulaire n’est enregistrée sur ce site.</p></form></div></section>
  </main>
  <footer class="footer"><div class="container footer-grid"><div>${brand()}<p>Un accompagnement de qualité.<br>Une ambition partagée : votre réussite.</p><a class="footer-social" href="https://www.instagram.com/${center.instagram}/" target="_blank" rel="noopener noreferrer" aria-label="Centre Joundi sur Instagram">${icon('instagram')}</a></div><div><h3>Le centre</h3><a href="#accueil">Accueil</a><a href="#centre">Notre approche</a><a href="#professeurs">Nos professeurs</a><a href="#galerie">La vie au centre</a></div><div><h3>Votre parcours</h3><a href="#matieres">Nos matières</a><a href="#planning">Planning</a><a href="#ressources">Ressources</a><a href="#contact">Contact</a></div><div><h3>Restons en contact</h3><a href="tel:+${center.whatsapp}">${escape(center.phone)}</a><a href="https://www.instagram.com/${center.instagram}/" target="_blank" rel="noopener noreferrer">@${center.instagram}</a><p>Hay El Salam<br>Safi, Maroc</p><a class="footer-register" href="${wa()}" target="_blank" rel="noopener noreferrer">S’inscrire ${icon('arrow')}</a></div></div><div class="container footer-bottom"><span>© ${new Date().getFullYear()} Centre Joundi. Tous droits réservés.</span><span>Le savoir aujourd’hui. L’avenir demain.</span></div></footer>
  <a class="floating-whatsapp" href="${wa()}" target="_blank" rel="noopener noreferrer" aria-label="Contacter Centre Joundi sur WhatsApp">${icon('whatsapp')}<span>Parlons de votre BAC</span></a>
  <dialog id="content-dialog" aria-labelledby="dialog-title"><div class="dialog-top"><h2 id="dialog-title"></h2><button class="dialog-close" aria-label="Fermer">${icon('close')}</button></div><div id="dialog-content"></div></dialog>
`;

const menuButton = document.querySelector('.menu-toggle');
const mobileNav = document.querySelector('#mobile-nav');
function closeMenu() { mobileNav.hidden = true; menuButton.setAttribute('aria-expanded', 'false'); menuButton.setAttribute('aria-label', 'Ouvrir le menu'); menuButton.innerHTML = icon('menu'); }
menuButton.addEventListener('click', () => { const open = menuButton.getAttribute('aria-expanded') !== 'true'; mobileNav.hidden = !open; menuButton.setAttribute('aria-expanded', String(open)); menuButton.setAttribute('aria-label', open ? 'Fermer le menu' : 'Ouvrir le menu'); menuButton.innerHTML = icon(open ? 'close' : 'menu'); });
mobileNav.addEventListener('click', e => { if (e.target.closest('a')) closeMenu(); });
document.addEventListener('keydown', e => { if (e.key === 'Escape' && !mobileNav.hidden) { closeMenu(); menuButton.focus(); } });
matchMedia('(min-width: 1180px)').addEventListener('change', e => { if (e.matches) closeMenu(); });
document.addEventListener('click', e => { if (!e.composedPath().includes(document.querySelector('.header'))) closeMenu(); });

document.querySelectorAll('[data-teacher-filter]').forEach(button => button.addEventListener('click', () => {
  document.querySelectorAll('[data-teacher-filter]').forEach(b => { b.classList.toggle('active', b === button); b.setAttribute('aria-pressed', String(b === button)); });
  const filtered = teachers.filter(t => button.dataset.teacherFilter === 'all' || t.levels.includes(button.dataset.teacherFilter));
  document.querySelector('#teacher-grid').innerHTML = filtered.map(teacherCard).join('');
  document.querySelector('#teacher-status').textContent = `${filtered.length} professeurs affichés`;
}));
let selectedLevel = '1BAC';
function renderSchedule() {
  const subject = document.querySelector('#schedule-subject').value;
  const matching = schedules.filter(s => s.level === selectedLevel && (subject === 'all' || s.subject === subject));
  document.querySelector('#schedule-grid').innerHTML = ['Lundi', 'Mardi', 'Mercredi', 'Jeudi', 'Vendredi', 'Samedi', 'Dimanche'].map(day => {
    const daily = matching.filter(s => s.day === day).sort((a, b) => a.start.localeCompare(b.start));
    return `<div class="schedule-day"><h3>${day}</h3><div>${daily.length ? daily.map(s => `<article class="schedule-event"><span>${escape(s.start)} – ${escape(s.end)}</span><strong>${escape(s.subject)}</strong><small>${escape(s.teacher)}</small></article>`).join('') : `<div class="schedule-empty"><span>—</span><small>${schedules.length ? 'Aucun cours publié' : 'À confirmer'}</small></div>`}</div></div>`;
  }).join('');
  document.querySelector('#schedule-notice').innerHTML = `${icon('calendar')}<p>${schedules.length ? `${matching.length} cours publié${matching.length > 1 ? 's' : ''} pour le niveau ${selectedLevel}. Contactez le centre pour confirmer votre inscription.` : `Le planning ${selectedLevel} sera publié prochainement. <a href="${wa(`Bonjour Centre Joundi, je souhaite recevoir le planning ${selectedLevel}${subject === 'all' ? '' : ` en ${subject}`}.`)}" target="_blank" rel="noopener noreferrer">Contactez-nous pour connaître les horaires.</a>`}</p>`;
}
document.querySelectorAll('[data-level]').forEach(button => button.addEventListener('click', () => { selectedLevel = button.dataset.level; document.querySelectorAll('[data-level]').forEach(b => { b.classList.toggle('active', b === button); b.setAttribute('aria-pressed', String(b === button)); }); renderSchedule(); }));
document.querySelector('#schedule-subject').addEventListener('change', renderSchedule);
renderSchedule();

const dialog = document.querySelector('#content-dialog');
function openDialog(title, content) { document.querySelector('#dialog-title').textContent = title; document.querySelector('#dialog-content').innerHTML = content; dialog.showModal(); document.body.classList.add('dialog-open'); }
document.querySelector('.dialog-close').addEventListener('click', () => dialog.close());
dialog.addEventListener('close', () => document.body.classList.remove('dialog-open'));
dialog.addEventListener('click', e => { const rect = dialog.getBoundingClientRect(); if (e.target === dialog && (e.clientX < rect.left || e.clientX > rect.right || e.clientY < rect.top || e.clientY > rect.bottom)) dialog.close(); });
document.querySelectorAll('[data-resource]').forEach(button => button.addEventListener('click', () => { const r = resources[Number(button.dataset.resource)]; openDialog(r.subject, r.documents.length ? `<ul class="document-list">${r.documents.map(d => `<li><a href="${escape(d.url)}" target="_blank" rel="noopener noreferrer">${icon('file')}<span><strong>${escape(d.title)}</strong><small>${escape(d.type)} · ${escape(d.level)} · PDF</small></span>${icon('arrow')}</a></li>`).join('')}</ul>` : `<div class="resource-empty">${icon('file')}<h3>Les ressources arrivent bientôt.</h3><p>Aucun document n’est encore publié pour cette matière. Contactez le centre pour connaître les supports disponibles.</p><a class="btn btn-primary" href="${wa(`Bonjour Centre Joundi, je souhaite des informations sur les ressources de ${r.subject}.`)}" target="_blank" rel="noopener noreferrer">Demander des informations ${icon('arrow')}</a></div>`); }));
document.querySelectorAll('[data-gallery]').forEach(button => button.addEventListener('click', () => { const g = gallery[Number(button.dataset.gallery)]; openDialog(g.caption || 'La vie au Centre Joundi', photo(g.src, g.alt, 'lightbox-image', true, g)); }));
document.querySelector('#contact-form').addEventListener('submit', e => {
  e.preventDefault();
  const data = new FormData(e.currentTarget);
  const message = `Bonjour Centre Joundi,\nJe m’appelle ${data.get('name').trim()}.\nTéléphone : ${data.get('phone').trim()}\nNiveau : ${data.get('level')}\nMatière : ${data.get('subject')}${data.get('message').trim() ? `\n\n${data.get('message').trim()}` : ''}\nJe souhaite des informations sur les cours et l’inscription.`;
  window.location.assign(wa(message));
});

const navObserver = new IntersectionObserver(entries => { for (const entry of entries) if (entry.isIntersecting) { document.querySelectorAll('.desktop-nav a').forEach(a => { const active = a.hash === `#${entry.target.id}`; a.classList.toggle('current', active); if (active) a.setAttribute('aria-current', 'location'); else a.removeAttribute('aria-current'); }); } }, { rootMargin: '-15% 0px -65% 0px' });
document.querySelectorAll('main section[id]').forEach(s => navObserver.observe(s));
if (!matchMedia('(prefers-reduced-motion: reduce)').matches) {
  const revealObserver = new IntersectionObserver(entries => { entries.forEach(entry => { if (entry.isIntersecting) { entry.target.classList.add('revealed'); revealObserver.unobserve(entry.target); } }); }, { threshold: 0.08 });
  document.querySelectorAll('.section-heading, .about-content, .registration-inner').forEach(el => { el.classList.add('reveal'); revealObserver.observe(el); });
}
const structuredData = document.createElement('script');
structuredData.type = 'application/ld+json';
structuredData.textContent = JSON.stringify({ '@context': 'https://schema.org', '@type': 'EducationalOrganization', name: center.name, telephone: '+' + center.whatsapp, address: { '@type': 'PostalAddress', streetAddress: center.address, addressLocality: 'Safi', addressCountry: 'MA' }, sameAs: [`https://www.instagram.com/${center.instagram}/`] });
document.head.append(structuredData);
